GET http://localhost:3001/users

###

GET http://localhost:3001/todos

###

GET http://localhost:3001/todos/getAllLists

###

POST http://localhost:3001/users/createUser
Content-Type: application/json

{
  "name": "phillip"
}

###

POST http://localhost:3001/todos/createList
Content-Type: application/json

{
  "name": "Basic list" 
}

###

POST http://localhost:3001/todos/createTodoItem/62520dee3fb782c07c5c61c0
Content-Type: application/json

{
  "itemString": "Basic todo"
}

###

PATCH  http://localhost:3001/todos/editTodoItem/62520fdeac04f54ae15c9de7
Content-Type: application/json

{
  "itemString": "finally",
  "completed": true
}

###

DELETE http://localhost:3001/todos/deleteTodoListItem/62520fdeac04f54ae15c9de7
Content-Type: application/json

### 


